# Generated by Django 4.2.4 on 2023-12-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='segments',
            field=models.ManyToManyField(blank=True, null=True, to='core.sessionpart'),
        ),
    ]
