# Generated by Django 4.2.4 on 2023-12-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_psychiatrist_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='segments',
            field=models.ManyToManyField(blank=True, to='core.sessionpart'),
        ),
    ]
