# Generated by Django 4.2.4 on 2023-12-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_session_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(upload_to='psych/'),
        ),
    ]
