# Generated by Django 4.2.4 on 2023-12-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_session_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesession',
            name='sessions',
            field=models.ManyToManyField(to='core.session'),
        ),
    ]
