# Generated by Django 4.2.4 on 2023-12-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_completedsessionduration_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='sessionpart',
            name='content_type',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Article', 'Article')], max_length=20, null=True),
        ),
    ]
