# Generated by Django 4.2.4 on 2023-12-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sessionpart_category_sessionpart_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedsessionduration',
            name='total_duration',
        ),
        migrations.AddField(
            model_name='completedsessionduration',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedsessionduration',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
