# Generated by Django 4.2.4 on 2023-12-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_completedsessionduration_total_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedsessionduration',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='completedsessionduration',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
