# Generated by Django 4.2.4 on 2024-01-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_completedsessionduration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('Breathing', 'Breathing'), ('Meditation', 'Meditation'), ('Relaxation', 'Relaxation')], max_length=20, null=True),
        ),
    ]
