# Generated by Django 4.2.4 on 2024-01-23 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RecentSessionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.ManyToManyField(to='core.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
