# Generated by Django 4.2.4 on 2024-01-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_session_date_added_session_number_of_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
