# Generated by Django 4.2.4 on 2023-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('hobby', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
