# Generated by Django 4.2.4 on 2023-09-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Reminder',
            new_name='reminder',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Repetition',
            new_name='repetition',
        ),
    ]
