# Generated by Django 4.2.4 on 2023-10-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_rename_description_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='Green', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
