# Generated by Django 4.2.4 on 2023-10-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_event_color_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='Not started', max_length=40),
        ),
    ]
