# Generated by Django 4.2.4 on 2023-12-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
