# Generated by Django 4.2.4 on 2023-12-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Success', 'Success'), ('Info', 'Info'), ('Alert', 'Alert'), ('Warning', 'Warning'), ('Reminder', 'Reminder')], default='Info', max_length=20),
        ),
    ]
