# Generated by Django 4.2.4 on 2024-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_remove_profile_profile_picture_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
