# Generated by Django 4.2.4 on 2024-04-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture_url',
        ),
    ]
